import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./(home)/_components/sidebar";
import { PlantsProvider } from "@/providers/plantprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Plantr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PlantsProvider>
        <body className={inter.className}>{children}</body>
      </PlantsProvider>
    </html>
  );
}
