import { Inter } from "next/font/google";
import "./globals.css";
import { PlantsProvider } from "@/providers/plantprovider";
import { UsersPlantsProvider } from "@/providers/users-plants-provider";
import Provider from "@/providers/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Plantr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <PlantsProvider>
          <UsersPlantsProvider>
            <body className={inter.className}>{children}</body>
          </UsersPlantsProvider>
        </PlantsProvider>
      </Provider>
    </html>
  );
}
